DROP TABLE IF EXISTS SCATBOROUGH.dbo.Equipment;

CREATE TABLE SCATBOROUGH.dbo.Equipment (
_EquipmentId	CHAR(8)	PRIMARY KEY
,_OwnerId CHAR(2)
,_PricelistId CHAR(8) NOT NULL
,_ReservationId CHAR(2)
,_SaleId CHAR(2)
,_RentalId CHAR(2)
--,_DateStart DATE
--,_DateEnd DATE
,_Milleage INT NOT NULL
,_AskingPrice INT NOT NULL
);

SELECT * FROM SCATBOROUGH.dbo.Equipment;

INSERT INTO SCATBOROUGH.dbo.Equipment VALUES(
'MT100001',NULL,'2020CHST',NULL,NULL,NULL,0,30000
);
INSERT INTO SCATBOROUGH.dbo.Equipment VALUES(
'MT100002','00','2020CHDM',NULL,'01',NULL,15000,90000
);
INSERT INTO SCATBOROUGH.dbo.Equipment VALUES(
'MT100003','00','2020RM15',NULL,'02',NULL,300,45000
);
SELECT * FROM SCATBOROUGH.dbo.Equipment;
