DROP TABLE IF EXISTS SCATBOROUGH.dbo.PartsPriceList;

CREATE TABLE SCATBOROUGH.dbo.PartsPriceList (
_SupplierId	CHAR(2)	NOT NULL
,_PartsPricelistId	CHAR(12) PRIMARY KEY
,_Name	VARCHAR(50) NOT NULL
,_UnitCost	INT NOT NULL
,_UnitSale	INT NOT NULL
);

SELECT * FROM SCATBOROUGH.dbo.PartsPriceList;

INSERT INTO SCATBOROUGH.dbo.PartsPriceList VALUES(
'00','2020CHXT-01','ChallengerSXT AIR FILTER',5,10
);
INSERT INTO SCATBOROUGH.dbo.PartsPriceList VALUES(
'00','2020CHRT-01','ChallengerRT AIR FILTER',10,20
);
INSERT INTO SCATBOROUGH.dbo.PartsPriceList VALUES(
'00','2020CHDM-01','ChallengerDM AIR FILTER',15,30
);
SELECT * FROM SCATBOROUGH.dbo.PartsPriceList;
